---
name: Enforce Open Source Community Standards
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  enforce-community-standards:
    uses: tektronix/python-package-ci-cd/.github/workflows/_reusable-enforce-community-standards.yml@3a82109ec91de73b4ea458037712eaf19607d392  # v1.3.0
