---
name: Publish API Breaking Change Check Results
on:
  workflow_run:
    workflows: [Check Public API for Breaking Changes]
    types: [completed]
jobs:
  publish-api-comparison:
    uses: tektronix/python-package-ci-cd/.github/workflows/_reusable-publish-api-comparison.yml@3a82109ec91de73b4ea458037712eaf19607d392  # v1.3.0
    permissions:
      checks: write
      pull-requests: write
