---
name: Create & Scan SBOM
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
jobs:
  sbom-scan:
    uses: tektronix/python-package-ci-cd/.github/workflows/_reusable-sbom-scan.yml@3a82109ec91de73b4ea458037712eaf19607d392  # v1.3.0
    permissions:
      security-events: write
      contents: write
      id-token: write
      attestations: write
