---
name: Test code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test-code:
    uses: tektronix/python-package-ci-cd/.github/workflows/_reusable-test-code.yml@3a82109ec91de73b4ea458037712eaf19607d392  # v1.3.0
    with:
      repo-name: tektronix/TekHSI
      operating-systems-array: '["ubuntu", "windows", "macos"]'
      python-versions-array: '["3.8", "3.9", "3.10", "3.11", "3.12"]'  # when updating this, make sure to update all workflows that use this strategy
      upload-to-codecov: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
